--------------------------------------------------------
--  File created - Friday-December-15-2023   
--------------------------------------------------------
--------------------------------------------------------
--  DDL for Table CUSTOMERS
--------------------------------------------------------

  CREATE TABLE "FINAL_2312873"."CUSTOMERS" 
   (	"CUSTOMER_ID" VARCHAR2(32 BYTE) DEFAULT SYS_GUID(), 
	"FIRSTNAME" VARCHAR2(30 BYTE), 
	"LASTNAME" VARCHAR2(30 BYTE), 
	"ADDRESS" VARCHAR2(30 BYTE), 
	"CITY" VARCHAR2(30 BYTE), 
	"POSTAL_CODE" VARCHAR2(7 BYTE), 
	"EMAIL" VARCHAR2(30 BYTE), 
	"PASSWORD" VARCHAR2(20 BYTE), 
	"CREATED_AT" TIMESTAMP (6) DEFAULT CURRENT_TIMESTAMP, 
	"MODIFIED_AT" TIMESTAMP (6) DEFAULT CURRENT_TIMESTAMP
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Table PRODUCTS
--------------------------------------------------------

  CREATE TABLE "FINAL_2312873"."PRODUCTS" 
   (	"PRODUCT_NUMBER" VARCHAR2(32 BYTE) DEFAULT SYS_GUID(), 
	"DESCRIPTION" VARCHAR2(50 BYTE), 
	"PRICE" NUMBER, 
	"CREATED_AT" TIMESTAMP (6) DEFAULT CURRENT_TIMESTAMP, 
	"MODIFIED_AT" TIMESTAMP (6) DEFAULT CURRENT_TIMESTAMP
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Table SALES
--------------------------------------------------------

  CREATE TABLE "FINAL_2312873"."SALES" 
   (	"QUANTITY_SOLD" NUMBER, 
	"TOTAL_PRICE" NUMBER, 
	"INVOICE_NUMBER" VARCHAR2(20 BYTE), 
	"SALES_ID" VARCHAR2(32 BYTE) DEFAULT SYS_GUID(), 
	"CUSTOMER_ID" VARCHAR2(20 BYTE), 
	"PRODUCT_ID" VARCHAR2(20 BYTE), 
	"CREATED_AT" TIMESTAMP (6) DEFAULT CURRENT_TIMESTAMP, 
	"MODIFIED_AT" TIMESTAMP (6) DEFAULT CURRENT_TIMESTAMP
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
REM INSERTING into FINAL_2312873.CUSTOMERS
SET DEFINE OFF;
Insert into FINAL_2312873.CUSTOMERS (CUSTOMER_ID,FIRSTNAME,LASTNAME,ADDRESS,CITY,POSTAL_CODE,EMAIL,PASSWORD,CREATED_AT,MODIFIED_AT) values ('1','Meet','Patel','V2, Signature ','Vapi','h4r1l7','meetp6118@gmail.com','sula6118',to_timestamp('15-12-23 10:04:17.598000000 AM','DD-MM-RR fmHH12:fmMI:SSXFF AM'),to_timestamp('15-12-23 10:04:17.598000000 AM','DD-MM-RR fmHH12:fmMI:SSXFF AM'));
Insert into FINAL_2312873.CUSTOMERS (CUSTOMER_ID,FIRSTNAME,LASTNAME,ADDRESS,CITY,POSTAL_CODE,EMAIL,PASSWORD,CREATED_AT,MODIFIED_AT) values ('2','Dev','Patel','44 Chandralok','vadodara','h7r8i6','dev@gmail.com','dev123',to_timestamp('15-12-23 10:04:17.605000000 AM','DD-MM-RR fmHH12:fmMI:SSXFF AM'),to_timestamp('15-12-23 10:04:17.605000000 AM','DD-MM-RR fmHH12:fmMI:SSXFF AM'));
Insert into FINAL_2312873.CUSTOMERS (CUSTOMER_ID,FIRSTNAME,LASTNAME,ADDRESS,CITY,POSTAL_CODE,EMAIL,PASSWORD,CREATED_AT,MODIFIED_AT) values ('3','Dhruv','Patel','304 Sheetal appartment','Mumbai','h8e5y7','dhruv@gmail.com','noob2103',to_timestamp('15-12-23 10:04:17.609000000 AM','DD-MM-RR fmHH12:fmMI:SSXFF AM'),to_timestamp('15-12-23 10:04:17.609000000 AM','DD-MM-RR fmHH12:fmMI:SSXFF AM'));
REM INSERTING into FINAL_2312873.PRODUCTS
SET DEFINE OFF;
Insert into FINAL_2312873.PRODUCTS (PRODUCT_NUMBER,DESCRIPTION,PRICE,CREATED_AT,MODIFIED_AT) values ('1','its a rice bag',60,to_timestamp('15-12-23 10:06:59.212000000 AM','DD-MM-RR fmHH12:fmMI:SSXFF AM'),to_timestamp('15-12-23 10:06:59.212000000 AM','DD-MM-RR fmHH12:fmMI:SSXFF AM'));
Insert into FINAL_2312873.PRODUCTS (PRODUCT_NUMBER,DESCRIPTION,PRICE,CREATED_AT,MODIFIED_AT) values ('2','it is oil',35,to_timestamp('15-12-23 10:06:59.219000000 AM','DD-MM-RR fmHH12:fmMI:SSXFF AM'),to_timestamp('15-12-23 10:06:59.219000000 AM','DD-MM-RR fmHH12:fmMI:SSXFF AM'));
Insert into FINAL_2312873.PRODUCTS (PRODUCT_NUMBER,DESCRIPTION,PRICE,CREATED_AT,MODIFIED_AT) values ('3','it is a beauty product',80,to_timestamp('15-12-23 10:06:59.224000000 AM','DD-MM-RR fmHH12:fmMI:SSXFF AM'),to_timestamp('15-12-23 10:06:59.224000000 AM','DD-MM-RR fmHH12:fmMI:SSXFF AM'));
REM INSERTING into FINAL_2312873.SALES
SET DEFINE OFF;
--------------------------------------------------------
--  DDL for Index PRODUCTS_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "FINAL_2312873"."PRODUCTS_PK" ON "FINAL_2312873"."PRODUCTS" ("PRODUCT_NUMBER") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index CUSTOMERS_UK1
--------------------------------------------------------

  CREATE UNIQUE INDEX "FINAL_2312873"."CUSTOMERS_UK1" ON "FINAL_2312873"."CUSTOMERS" ("EMAIL") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index CUSTOMERS_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "FINAL_2312873"."CUSTOMERS_PK" ON "FINAL_2312873"."CUSTOMERS" ("CUSTOMER_ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Trigger TRIGGER1
--------------------------------------------------------

  CREATE OR REPLACE EDITIONABLE TRIGGER "FINAL_2312873"."TRIGGER1" 
BEFORE UPDATE OF POSTAL_CODE ON CUSTOMERS 
FOR EACH ROW
DECLARE
    v_pattern VARCHAR2(7) := '^[A-Za-z]\d[A-Za-z]\d[A-Za-z]\d$';
BEGIN
    IF :NEW.postal_code IS NOT NULL AND
       REGEXP_LIKE(:NEW.postal_code, v_pattern) = FALSE THEN
        RAISE_APPLICATION_ERROR(-20001, 'Invalid postal code format. Must be in the format "H3Y4R4".');
    END IF;
END;
/
ALTER TRIGGER "FINAL_2312873"."TRIGGER1" ENABLE;
--------------------------------------------------------
--  DDL for Procedure DELETE_CUSTOMER
--------------------------------------------------------
set define off;

  CREATE OR REPLACE EDITIONABLE PROCEDURE "FINAL_2312873"."DELETE_CUSTOMER" (
    p_customer_id NUMBER,
    p_firstname VARCHAR2,
    p_lastname VARCHAR2,
    p_email VARCHAR2,
    p_password VARCHAR2,
    p_city VARCHAR2,
    p_address VARCHAR2
)
AS 
BEGIN
    DELETE FROM Customers WHERE customer_id = p_customer_id;
    COMMIT;
END DELETE_CUSTOMER;

/
--------------------------------------------------------
--  DDL for Procedure UPDATE_CUSTOMER
--------------------------------------------------------
set define off;

  CREATE OR REPLACE EDITIONABLE PROCEDURE "FINAL_2312873"."UPDATE_CUSTOMER" (
    p_customer_id NUMBER,
    p_firstname VARCHAR2,
    p_lastname VARCHAR2,
    p_email VARCHAR2,
    p_password VARCHAR2,
    p_city VARCHAR2,
    p_address VARCHAR2
)
AS 
BEGIN
UPDATE Customers
    SET
        firstname=p_firstname,
        lastname=p_lastname,
        email=p_email,
        password=p_password,
        city=p_city,
        address=p_address
    WHERE customer_id = p_customer_id;
END UPDATE_CUSTOMER;

/
--------------------------------------------------------
--  DDL for Function CALC_TOTALPRICE
--------------------------------------------------------

  CREATE OR REPLACE EDITIONABLE FUNCTION "FINAL_2312873"."CALC_TOTALPRICE" (
    p_price DECIMAL,
    p_quantity INT
)
RETURN NUMBER AS v_total_price NUMBER;
BEGIN
  v_total_price := p_price * p_quantity;

  RETURN v_total_price;
END CALC_TOTALPRICE;

/
--------------------------------------------------------
--  DDL for Function SEARCH_CUSTOMERLN
--------------------------------------------------------

  CREATE OR REPLACE EDITIONABLE FUNCTION "FINAL_2312873"."SEARCH_CUSTOMERLN" (
    p_last_name_pattern VARCHAR2
)
RETURN SYS_REFCURSOR AS cur SYS_REFCURSOR;
BEGIN
 OPEN cur FOR
        SELECT *
        FROM Customers
        WHERE LOWER(lastname) LIKE LOWER(p_last_name_pattern || '%'); -- case-insensitive search
    RETURN cur;
END SEARCH_CUSTOMERLN;

/
--------------------------------------------------------
--  Constraints for Table CUSTOMERS
--------------------------------------------------------

  ALTER TABLE "FINAL_2312873"."CUSTOMERS" MODIFY ("CUSTOMER_ID" NOT NULL ENABLE);
  ALTER TABLE "FINAL_2312873"."CUSTOMERS" MODIFY ("FIRSTNAME" NOT NULL ENABLE);
  ALTER TABLE "FINAL_2312873"."CUSTOMERS" MODIFY ("LASTNAME" NOT NULL ENABLE);
  ALTER TABLE "FINAL_2312873"."CUSTOMERS" MODIFY ("ADDRESS" NOT NULL ENABLE);
  ALTER TABLE "FINAL_2312873"."CUSTOMERS" MODIFY ("CITY" NOT NULL ENABLE);
  ALTER TABLE "FINAL_2312873"."CUSTOMERS" MODIFY ("POSTAL_CODE" NOT NULL ENABLE);
  ALTER TABLE "FINAL_2312873"."CUSTOMERS" MODIFY ("EMAIL" NOT NULL ENABLE);
  ALTER TABLE "FINAL_2312873"."CUSTOMERS" MODIFY ("PASSWORD" NOT NULL ENABLE);
  ALTER TABLE "FINAL_2312873"."CUSTOMERS" ADD CONSTRAINT "CUSTOMERS_PK" PRIMARY KEY ("CUSTOMER_ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
  ALTER TABLE "FINAL_2312873"."CUSTOMERS" ADD CONSTRAINT "CUSTOMERS_UK1" UNIQUE ("EMAIL")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
  ALTER TABLE "FINAL_2312873"."CUSTOMERS" MODIFY ("CREATED_AT" NOT NULL ENABLE);
  ALTER TABLE "FINAL_2312873"."CUSTOMERS" MODIFY ("MODIFIED_AT" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table PRODUCTS
--------------------------------------------------------

  ALTER TABLE "FINAL_2312873"."PRODUCTS" MODIFY ("PRODUCT_NUMBER" NOT NULL ENABLE);
  ALTER TABLE "FINAL_2312873"."PRODUCTS" MODIFY ("DESCRIPTION" NOT NULL ENABLE);
  ALTER TABLE "FINAL_2312873"."PRODUCTS" MODIFY ("PRICE" NOT NULL ENABLE);
  ALTER TABLE "FINAL_2312873"."PRODUCTS" ADD CONSTRAINT "PRODUCTS_PK" PRIMARY KEY ("PRODUCT_NUMBER")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
  ALTER TABLE "FINAL_2312873"."PRODUCTS" MODIFY ("CREATED_AT" NOT NULL ENABLE);
  ALTER TABLE "FINAL_2312873"."PRODUCTS" MODIFY ("MODIFIED_AT" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table SALES
--------------------------------------------------------

  ALTER TABLE "FINAL_2312873"."SALES" MODIFY ("QUANTITY_SOLD" NOT NULL ENABLE);
  ALTER TABLE "FINAL_2312873"."SALES" MODIFY ("TOTAL_PRICE" NOT NULL ENABLE);
  ALTER TABLE "FINAL_2312873"."SALES" MODIFY ("INVOICE_NUMBER" NOT NULL ENABLE);
  ALTER TABLE "FINAL_2312873"."SALES" MODIFY ("SALES_ID" NOT NULL ENABLE);
  ALTER TABLE "FINAL_2312873"."SALES" MODIFY ("CUSTOMER_ID" NOT NULL ENABLE);
  ALTER TABLE "FINAL_2312873"."SALES" MODIFY ("PRODUCT_ID" NOT NULL ENABLE);
  ALTER TABLE "FINAL_2312873"."SALES" MODIFY ("CREATED_AT" NOT NULL ENABLE);
  ALTER TABLE "FINAL_2312873"."SALES" MODIFY ("MODIFIED_AT" NOT NULL ENABLE);
--------------------------------------------------------
--  Ref Constraints for Table SALES
--------------------------------------------------------

  ALTER TABLE "FINAL_2312873"."SALES" ADD CONSTRAINT "SALES_FK1" FOREIGN KEY ("INVOICE_NUMBER")
	  REFERENCES "FINAL_2312873"."PRODUCTS" ("PRODUCT_NUMBER") ENABLE;
  ALTER TABLE "FINAL_2312873"."SALES" ADD CONSTRAINT "SALES_FK2" FOREIGN KEY ("CUSTOMER_ID")
	  REFERENCES "FINAL_2312873"."CUSTOMERS" ("CUSTOMER_ID") ENABLE;
