SPOOL C:\DATABASE\Meet_FINAL.txt
SELECT to_char(sysdate,'Day DD Month Year HH:MI:SS Am' ) FROM dual;

DROP TABLE ADVISOR CASCADE;
DROP TABLE STUDENT CASCADE;
DROP TABLE ENROLLMENT CASCADE;
DROP TABLE COURSE CASCADE;

CREATE TABLE ADVISOR(AdvisorID NUMBER, AdvisorName VARCHAR2(40));
ALTER TABLE ADVISOR
ADD CONSTRAINT Advisor_AdvisorID_PK PRIMARY KEY (AdvisorID);
ALTER TABLE  ADVISOR
MODIFY (AdvisorName CONSTRAINT ADVISOR_AdvisorName_NN NOT NULL);

CREATE TABLE STUDENT(StudentID NUMBER, StudentName VARCHAR2(40), Birthdate DATE, AdvisorID NUMBER);
ALTER TABLE STUDENT
ADD CONSTRAINT STUDENT_StudentID_PK PRIMARY KEY (StudentID);
ALTER TABLE  STUDENT
ADD CONSTRAINT STUDENT_AdvisorID_FK FOREIGN KEY (AdvisorID)
REFERENCES ADVISOR (AdvisorID);
ALTER TABLE  STUDENT
MODIFY (StudentName CONSTRAINT STUDENT_StudentName_NN NOT NULL);


CREATE TABLE COURSE(CourseID NUMBER, CourseTitle VARCHAR2(40), Credits NUMBER);
ALTER TABLE COURSE
ADD CONSTRAINT COURSE_CourseID_PK PRIMARY KEY (CourseID);

CREATE TABLE ENROLLMENT(StudentID NUMBER, CourseID NUMBER, GRADE NUMBER, 
CONSTRAINT ENROLLMENT_StudentID_CourseID_PK PRIMARY KEY (StudentID,CourseID) );
 
ALTER TABLE ENROLLMENT
ADD CONSTRAINT ENROLLMENT_StudentID_FK FOREIGN KEY (StudentID)
REFERENCES STUDENT (StudentID);
ALTER TABLE ENROLLMENT
ADD CONSTRAINT ENROLLMENT_CourseID_FK FOREIGN KEY (CourseID)
REFERENCES COURSE (CourseID);

ALTER TABLE STUDENT
ADD(GENDER CHAR(1) );

ALTER TABLE STUDENT
ADD CONSTRAINT STUDENT_GENDER_CC CHECK (GENDER IN('M','m','F','f'));

ALTER TABLE COURSE
MODIFY (Credits NUMBER CONSTRAINT COURSE_Credits_CC CHECK (Credits >= 0)) ;

ALTER TABLE COURSE
ADD CONSTRAINT COURSE_CourseTitle_UK UNIQUE (CourseTitle);


SELECT table_name FROM user_tables;

DESCRIBE COURSE
DESCRIBE ADVISOR
DESCRIBE STUDENT
DESCRIBE ENROLLMENT

SELECT constraint_name, table_name, constraint_type FROM user_constraints;


SPOOL OFF;
